#include "VoltaFramework.hpp"
#include <unordered_map>

static const std::unordered_map<std::string, int> keyMap {
    {"a", GLFW_KEY_A}, {"b", GLFW_KEY_B}, {"c", GLFW_KEY_C}, {"d", GLFW_KEY_D},
    {"e", GLFW_KEY_E}, {"f", GLFW_KEY_F}, {"g", GLFW_KEY_G}, {"h", GLFW_KEY_H},
    {"i", GLFW_KEY_I}, {"j", GLFW_KEY_J}, {"k", GLFW_KEY_K}, {"l", GLFW_KEY_L},
    {"m", GLFW_KEY_M}, {"n", GLFW_KEY_N}, {"o", GLFW_KEY_O}, {"p", GLFW_KEY_P},
    {"q", GLFW_KEY_Q}, {"r", GLFW_KEY_R}, {"s", GLFW_KEY_S}, {"t", GLFW_KEY_T},
    {"u", GLFW_KEY_U}, {"v", GLFW_KEY_V}, {"w", GLFW_KEY_W}, {"x", GLFW_KEY_X},
    {"y", GLFW_KEY_Y}, {"z", GLFW_KEY_Z},
    {"0", GLFW_KEY_0}, {"1", GLFW_KEY_1}, {"2", GLFW_KEY_2}, {"3", GLFW_KEY_3},
    {"4", GLFW_KEY_4}, {"5", GLFW_KEY_5}, {"6", GLFW_KEY_6}, {"7", GLFW_KEY_7},
    {"8", GLFW_KEY_8}, {"9", GLFW_KEY_9},
    {"space", GLFW_KEY_SPACE}, {"escape", GLFW_KEY_ESCAPE}, {"enter", GLFW_KEY_ENTER},
    {"tab", GLFW_KEY_TAB}, {"backspace", GLFW_KEY_BACKSPACE}, {"insert", GLFW_KEY_INSERT},
    {"delete", GLFW_KEY_DELETE}, {"right", GLFW_KEY_RIGHT}, {"left", GLFW_KEY_LEFT},
    {"down", GLFW_KEY_DOWN}, {"up", GLFW_KEY_UP}, {"pageup", GLFW_KEY_PAGE_UP},
    {"pagedown", GLFW_KEY_PAGE_DOWN}, {"home", GLFW_KEY_HOME}, {"end", GLFW_KEY_END},
    {"capslock", GLFW_KEY_CAPS_LOCK}, {"scrolllock", GLFW_KEY_SCROLL_LOCK}, {"printscreen", GLFW_KEY_PRINT_SCREEN},
    {"numlock", GLFW_KEY_NUM_LOCK}, {"pause", GLFW_KEY_PAUSE},
    {"f1", GLFW_KEY_F1}, {"f2", GLFW_KEY_F2}, {"f3", GLFW_KEY_F3}, {"f4", GLFW_KEY_F4},
    {"f5", GLFW_KEY_F5}, {"f6", GLFW_KEY_F6}, {"f7", GLFW_KEY_F7}, {"f8", GLFW_KEY_F8},
    {"f9", GLFW_KEY_F9}, {"f10", GLFW_KEY_F10}, {"f11", GLFW_KEY_F11}, {"f12", GLFW_KEY_F12},
    {"kp0", GLFW_KEY_KP_0}, {"kp1", GLFW_KEY_KP_1}, {"kp2", GLFW_KEY_KP_2},
    {"kp3", GLFW_KEY_KP_3}, {"kp4", GLFW_KEY_KP_4}, {"kp5", GLFW_KEY_KP_5},
    {"kp6", GLFW_KEY_KP_6}, {"kp7", GLFW_KEY_KP_7}, {"kp8", GLFW_KEY_KP_8},
    {"kp9", GLFW_KEY_KP_9}, {"kpdecimal", GLFW_KEY_KP_DECIMAL},
    {"kpdivide", GLFW_KEY_KP_DIVIDE}, {"kpmultiply", GLFW_KEY_KP_MULTIPLY},
    {"kpsubtract", GLFW_KEY_KP_SUBTRACT}, {"kpadd", GLFW_KEY_KP_ADD},
    {"kpenter", GLFW_KEY_KP_ENTER}, {"kpequal", GLFW_KEY_KP_EQUAL},
    {"leftshift", GLFW_KEY_LEFT_SHIFT}, {"leftcontrol", GLFW_KEY_LEFT_CONTROL},
    {"leftalt", GLFW_KEY_LEFT_ALT}, {"leftsuper", GLFW_KEY_LEFT_SUPER},
    {"rightshift", GLFW_KEY_RIGHT_SHIFT}, {"rightcontrol", GLFW_KEY_RIGHT_CONTROL},
    {"rightalt", GLFW_KEY_RIGHT_ALT}, {"rightsuper", GLFW_KEY_RIGHT_SUPER},
    {"menu", GLFW_KEY_MENU}, {"grave", GLFW_KEY_GRAVE_ACCENT}, {"semicolon", GLFW_KEY_SEMICOLON},
    {"apostrophe", GLFW_KEY_APOSTROPHE}, {"comma", GLFW_KEY_COMMA}, {"period", GLFW_KEY_PERIOD},
    {"slash", GLFW_KEY_SLASH}, {"backslash", GLFW_KEY_BACKSLASH}, {"minus", GLFW_KEY_MINUS},
    {"equal", GLFW_KEY_EQUAL}, {"leftbracket", GLFW_KEY_LEFT_BRACKET},
    {"rightbracket", GLFW_KEY_RIGHT_BRACKET}
};